# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\BarUSer:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        my_provider:
            entity:
                class: AppBundle:BarUser
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            logout_on_user_change: true
            anonymous: ~
            form_login:
                provider: my_provider
                login_path: login
                check_path: login
                default_target_path: dashboard
                always_use_default_target_path: true
            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/webhook, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/pay, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/process, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: ROLE_ADMIN }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER }